/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20MockSol from "./ERC20Mock.sol";
export { ERC1155Mock__factory } from "./ERC1155Mock__factory";
